FORMAT: 1A
HOST: http://www.google.com

# Sochi 2014 Winter Olympics
Documentation for our Olympics website

# Group Athletes
Athletes related resources. An athlete object has the following attributes:

* First Name
* Last Name
* Country
* Gender
* Date of Birth
* Gold Medals
* Silver Medals
* Bronze Medals


## /athletes
### List of all athletes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

## /athletes/{id}
### Retrieve an Athlete [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Athlete to perform action with. Has example value.
    

# Group Countries
Countries related resources. A country has the following attributes:

* Name
* Description
* Total Gold Medals
* Total of Silver Medals
* Total of Bronze Medals
* List of Athletes
* Sports participated
* Flag

## /countries
### List of all Countries [GET]
+ Response 200 (application/json)

## /countries/{id}
### Retrieve a Country [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Athlete to perform action with. Has example value.
    

# Group Events
Events related resources. An event has the following attributes:

* Name
* Sport(s) associated
* Description
* Gold Medalist(s)
* Silver Medalist(s)
* Bronze Medalist(s)

## /events
### List of all Events & associated Sports [GET]
+ Response 200 (application/json)

## /events/{id}
### Retrieve an event [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Athlete to perform action with. Has example value.
    
